name: stupid_simple_sheet_example
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1
resolution: workspace

environment:
  sdk: ^3.5.4
  flutter: ^3.27.0

dependencies:
  auto_route: ^10.0.1
  flutter:
    sdk: flutter
  liquid_glass_renderer:
    git:
      url: https://github.com/whynotmake-it/flutter_liquid_glass
      path: packages/liquid_glass_renderer
      ref: 2c5f88acefea99d4d7e22663946b623adc06bc3c
  stupid_simple_sheet:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
