name: heroine
description: The queen of hero transitions. Flutter's most addictive interactions.
version: 0.7.0
resolution: workspace

repository: https://github.com/whynotmake-it/rivership/tree/main/packages/heroine
homepage: https://whynotmake.it

topics: [springs, animation, physics, hero]

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  equatable: ">=2.0.0 <3.0.0"
  flutter:
    sdk: flutter
  motor: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lintervention: ^0.4.0+1
  mocktail: ^1.0.3
