name: snaptest
description: Snap photos in your widget tests.
version: 0.2.2+1
resolution: workspace
topics: ["testing", "golden", "screenshots", "automation"]

repository: https://github.com/whynotmake-it/rivership/tree/main/packages/snaptest
homepage: https://whynotmake.it
screenshots:
  - description: "A title banner that illustrates the main usage of the package."
    path: doc/banner.jpg  

environment:
  sdk: ">=3.8.0 <4.0.0"

dev_dependencies:
  google_fonts: ^6.2.1
  lintervention: ^0.3.1
  mocktail: ^1.0.3

dependencies:
  args: ^2.4.0
  device_frame: ">=1.0.0 <2.0.0"
  equatable: ">=2.0.0 <3.0.0"
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ">=1.15.0 <2.0.0"
  path: ">=1.0.0 <2.0.0"
  test_api: ">=0.5.0 <0.8.0"

executables:
  assemble: assemble
  clean: clean
