name: rivership_test
description: A package containing testing utilites to accompany the rivership package.
version: 0.2.0
resolution: workspace
repository: https://github.com/whynotmake-it/rivership/tree/main/packages/rivership_test
homepage: https://whynotmake.it

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  clock: ">=1.1.1 <2.0.0"
  fake_async: ">=1.3.1 <2.0.0"
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  hooks_riverpod: ^3.0.0
  mocktail: ">=1.0.4 <2.0.0"

dev_dependencies:
  lintervention: ^0.3.1
  
