name: springster
description: Spring animations and simulations, simplified.
version: 0.2.1
repository: https://github.com/whynotmake-it/rivership/tree/main/packages/springster
homepage: https://whynotmake.it

topics: [spring, animation, physics]

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lintervention: ^0.1.1
  mocktail: ^1.0.3
  spot: ^0.16.0
