name: rivership
description: An opinionated infrastructure package for use with hooks_riverpod.
version: 0.3.0+1
resolution: workspace
repository: https://github.com/whynotmake-it/rivership/tree/main/packages/rivership
homepage: https://whynotmake.it

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ">=0.21.2 <0.22.0"
  heroine: ^0.5.0+1
  hooks_riverpod: ^3.0.0
  intl: ">=0.19.0 <0.21.0"
  material_color_utilities: ">=0.8.0 <0.12.0"
  motor: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lintervention: ^0.3.1
  mocktail: ^1.0.3
  rivership_test: ^0.1.0+4
